name: Build and push Docker image to ECR
on:
  push:
    branches:
      - main
jobs:
  use-atlas-cli:
    runs-on: ubuntu-latest
    
    steps:
      - name: Configure Atlas CLI
        uses: andreaangiolillo/atlas-cli-github-action@v1.1.0
        with:
         public-key: vikvqvrh
         private-key: 643baf7961e6283573a0360d
         
      - name: Use AtlasCLI
        shell: bash
        run: atlas --version
          

     

  
    







    
