name: Build and push Docker image to ECR
on:
  push:
    branches:
      - main
env:
  MONGODB_ATLAS_USERNAME: ayush vashistha
  
  MONGODB_ATLAS_PROJECT_ID: 643baf793ce9aa61105a26c1
  MONGODB_ATLAS_CLUSTER_NAME: ayush-test
  
  MONGODB_ATLAS_FUNCTION_NAME: ayush_function
  #FILE_PATH: index.js
jobs:
  use-atlas-cli:
    runs-on: ubuntu-latest
    
    steps:
      - name: Configure Atlas CLI
        uses: andreaangiolillo/atlas-cli-github-action@v1.1.0
        with:
         public-key: vikvqvrh
         private-key: 643baf7961e6283573a0360d
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Use AtlasCLI
        shell: bash
        run: atlas --version
      - name: Upload File to Atlas Function
        uses: wei/curl@v1
        env:
          ATLAS_PUBLIC_KEY: vikvqvrh
          ATLAS_PRIVATE_KEY: 643baf7961e6283573a0360d
          ATLAS_PROJECT_ID: 643baf7961e6283573a0360d
          ATLAS_CLUSTER_NAME: ayush-test
        with:
          url: https://cloud.mongodb.com/api/atlas/v1.0/groups/${{ env.ATLAS_PROJECT_ID }}/clusters/${{ env.ATLAS_CLUSTER_NAME }}/functions/ayush_function/source
          method: POST
          user: ${{ env.ATLAS_PUBLIC_KEY }}:${{ env.ATLAS_PRIVATE_KEY }}
          header: |
            Content-Type: application/javascript
          data: |
            {{#readFile 'App.js'}}
            {{/readFile}}








       
      
    







    
